language: python
python:
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install .[test]

script:
  - pytest --cov=wxcast
  - flake8 tests/
  - flake8 wxcast/

notifications:
  email:
    on_success: change
    on_failure: change
