language: python
python:
  - "3.6"

install:
  - pip install .
  - pip install pytest
  - pip install flake8

script:
  - pytest --cov=wxcast
  - flake8 tests/
  - flake8 wxcast/

notifications:
  email:
    on_success: change
    on_failure: change
